string=str(input("enter any string:"))
print("the original string is :",string)
res=len(string.split())
print("the number of words in that sentence is:",str(res))
print("the number of charectors in that sentence is:",len(string))
